# Generated by Django 4.2.5 on 2023-09-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of creating')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('dead_line', models.DateTimeField(verbose_name='Time of dead line')),
                ('status', models.CharField(choices=[('C', 'completed'), ('N', 'not completed yet'), ('F', 'fail'), ('D', 'delayed')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
