# Generated by Django 4.2.5 on 2023-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of creating')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of last update')),
                ('dead_line', models.DateTimeField(verbose_name='Time of dead line')),
                ('status', models.CharField(choices=[('N', 'not completed yet'), ('C', 'completed'), ('F', 'fail'), ('D', 'delayed')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'not completed yet'), ('C', 'completed'), ('F', 'fail'), ('D', 'delayed')], max_length=1),
        ),
    ]
